Repository takapi327/ldbc, pull requests merged in 2024-05, with the labels that each got.

#198 Refactor/2024 04 fix connection
  database/connector_test.sql
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/Connection.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/DatabaseMetaData.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/ResultSet.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/ResultSetMetaData.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/Constants.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/MysqlType.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/RowIdLifetime.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/Types.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/HostInfo.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/Protocol.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/package.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/ResultSetRowPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/PreparedStatement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/Statement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/sql/SQLType.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ConnectionTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ResultSetTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/TransactionTest.scala
Labels: 🪲 bug, 🔧 refactor

#199 Refactor/2024 04 fix statement
  docs/src/main/mdoc/en/09-Connector.md
  docs/src/main/mdoc/ja/09-Connector.md
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/Connection.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/DatabaseMetaData.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/ResultSet.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/BinaryProtocolResultSetRowPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/PreparedStatement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/Statement.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ServerPreparedStatementQueryTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ServerPreparedStatementUpdateTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/StatementQueryTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/StatementUpdateTest.scala
Labels: 🔧 refactor

#201 Update circe-generic from 0.14.6 to 0.14.7
  build.sbt
  project/Dependencies.scala
Labels: ⛓️ dependencies

#202 Update otel4s-core-trace from 0.6.0 to 0.7.0
  build.sbt
Labels: ⛓️ dependencies

#200 Update mysql-connector-j from 8.3.0 to 8.4.0
  project/Dependencies.scala
Labels: ⛓️ dependencies

#204 Update sbt-typelevel from 0.7.0 to 0.7.1
  project/plugins.sbt
Labels: ⛓️ dependencies

#203 Update munit-cats-effect from 2.0.0-M5 to 2.0.0-RC1
  build.sbt
Labels: ⛓️ dependencies

#205 Feature/2024 04 create callable statement
  README.md
  database/connector_test.sql
  docs/src/main/mdoc/en/09-Connector.md
  docs/src/main/mdoc/ja/09-Connector.md
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/Connection.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/DatabaseMetaData.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/ResultSet.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/Parameter.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/CallableStatement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/sql/ParameterMetaData.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/util/StringHelper.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/CallableStatementTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ConnectionTest.scala
Labels: 🚀 feature

#206 Match the ldbc sql package to ldbc connector.
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/CallableStatement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/PreparedStatement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/Statement.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/StatementUpdateTest.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/Alias.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/PreparedStatement.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/SQLType.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/internal/CallableStatementSyntax.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/internal/ConnectionSyntax.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/internal/DatabaseMetaDataSyntax.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/internal/ParameterMetaDataSyntax.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/internal/ResultSetMetaDataSyntax.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/internal/ResultSetSyntax.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/internal/StatementSyntax.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/internal/package.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/syntax/CommandSyntax.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/syntax/SQLSyntax.scala
  module/ldbc-dsl/shared/src/test/scala/ldbc/dsl/ParameterBinderTest.scala
  module/ldbc-dsl/shared/src/test/scala/ldbc/dsl/schema/City.scala
  module/ldbc-dsl/shared/src/test/scala/ldbc/dsl/schema/GovernmentOffice.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/CallableStatement.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/Connection.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/DatabaseMetaData.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/Parameter.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/ParameterMetaData.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/PreparedStatement.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/ResultSet.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/ResultSetMetaData.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/ResultSetReader.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/RowIdLifetime.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/SQLType.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/Statement.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/package.scala
Labels: 🔧 refactor

#207 Update scala3-library from 3.4.1 to 3.4.2
  .github/workflows/ci.yml
  project/Versions.scala
Labels: ⛓️ dependencies

#208 Refactor/2024 05 remove cora package dependency from sql package
  build.sbt
  module/ldbc-dsl/shared/src/test/scala/ldbc/dsl/schema/Country.scala
  module/ldbc-dsl/shared/src/test/scala/ldbc/dsl/schema/CountryLanguage.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/Parameter.scala
Labels: 🔧 refactor

#209 Refactor/2024 05 Integration with sql package
  build.sbt
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/Connection.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/ConnectionImpl.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/DatabaseMetaData.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/DatabaseMetaDataImpl.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/LdbcConnection.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/ResultSet.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/ResultSetImpl.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/ResultSetMetaData.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/ResultSetMetaDataImpl.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/MysqlType.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/RowIdLifetime.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/CallableStatement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/CallableStatementImpl.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/ClientPreparedStatement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/PreparedStatement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/ServerPreparedStatement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/SharedPreparedStatement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/Statement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/StatementImpl.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/sql/ParameterMetaData.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/sql/SQLType.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/CallableStatementTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ClientPreparedStatementQueryTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ClientPreparedStatementUpdateTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ConnectionTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ResultSetTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/SavepointTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ServerPreparedStatementQueryTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ServerPreparedStatementUpdateTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/StatementBatchTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/StatementQueryTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/StatementUpdateTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/TransactionTest.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/internal/ConnectionSyntax.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/internal/DatabaseMetaDataSyntax.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/internal/ResultSetMetaDataSyntax.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/internal/ResultSetSyntax.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/syntax/CommandSyntax.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/syntax/SQLSyntax.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/Connection.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/DatabaseMetaData.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/ParameterMetaData.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/ResultSet.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/ResultSetMetaData.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/Statement.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/Types.scala
Labels: 🔧 refactor

#210 Refactor/2024 05 integration savepoint
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/ConnectionImpl.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/LdbcConnection.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/MysqlSavepoint.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/util/StringHelper.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/SavepointTest.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/internal/ConnectionSyntax.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/internal/SavepointSyntax.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/Connection.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/Savepoint.scala
Labels: 🔧 refactor

#211 Feature/2024 05 create sql string context
  benchmark/src/main/scala/benchmark/ldbc/Insert.scala
  benchmark/src/main/scala/benchmark/ldbc/Select.scala
  docs/src/main/mdoc/en/04-Database-Connection.md
  docs/src/main/mdoc/ja/04-Database-Connection.md
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/Mysql.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/package.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/SQLStringContextQueryTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/SQLStringContextUpdateTest.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/ConnectionProvider.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/Mysql.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/SQL.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/logging/ConsoleLogHandler.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/package.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/syntax/CommandSyntax.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/syntax/QuerySyntax.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/syntax/SQLSyntax.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/syntax/StringContextSyntax.scala
  module/ldbc-dsl/shared/src/test/scala/ldbc/dsl/DDLTest.scala
  module/ldbc-dsl/shared/src/test/scala/ldbc/dsl/DatabaseConnectionTest.scala
  module/ldbc-dsl/shared/src/test/scala/ldbc/dsl/DatabaseTest.scala
  module/ldbc-dsl/shared/src/test/scala/ldbc/dsl/ParameterBinderTest.scala
  module/ldbc-dsl/shared/src/test/scala/ldbc/dsl/syntax/QuerySyntaxTest.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/SQL.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/logging/LogEvent.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/logging/LogHandler.scala
Labels: 🚀 feature, project:sql, ldbc:connector

#214 Feature/2024 05 convenience method added for sql construction
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/Mysql.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/package.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/SQLStringContextQueryTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/SQLStringContextUpdateTest.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/Mysql.scala
  module/ldbc-dsl/shared/src/main/scala/ldbc/dsl/syntax/StringContextSyntax.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/SQL.scala
Labels: 🚀 feature, project:sql, project:dsl, ldbc:connector

#213 Update munit-cats-effect from 2.0.0-RC1 to 2.0.0
  build.sbt
Labels: ⛓️ dependencies

#216 Refactor/2024 05 OKPacket decode
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/ConnectionImpl.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/DatabaseMetaDataImpl.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/OKPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/CallableStatementImpl.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/ClientPreparedStatement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/ServerPreparedStatement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/StatementImpl.scala
Labels: 🔧 refactor, ldbc:connector

#219 Enhancement/2024 05 add large update
  module/jdbc-connector/src/main/scala/jdbc/connector/PreparedStatementImpl.scala
  module/jdbc-connector/src/main/scala/jdbc/connector/StatementImpl.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/exception/BatchUpdateException.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/ERRPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/CallableStatementImpl.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/ClientPreparedStatement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/ServerPreparedStatement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/SharedPreparedStatement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/StatementImpl.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/PreparedStatement.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/Statement.scala
Labels: 💪 enhancement, project:sql, ldbc:connector, jdbc:connector
