Repository takapi327/ldbc, pull requests merged in 2024-09, with the labels that each got.

#286 Update otel4s-core-trace from 0.8.1 to 0.9.0
  build.sbt
Labels: ⛓️ dependencies

#287 Update circe-generic from 0.14.9 to 0.14.10
  build.sbt
Labels: ⛓️ dependencies

#285 Refactor/2024 08 modification codec
  module/ldbc-dsl/src/main/scala/ldbc/dsl/Executor.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/Mysql.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/Parameter.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/Query.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/ResultSetConsumer.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/SQL.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/codec/Decoder.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/codec/Encoder.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/package.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/syntax/StringContextSyntax.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/Column.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/Table.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/Delete.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/Expression.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/GroupBy.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/Having.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/Insert.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/Join.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/Limit.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/Offset.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/OrderBy.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/Select.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/Update.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/Where.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/package.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/syntax/CommandSyntax.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/syntax/package.scala
  tests/src/main/scala/ldbc/tests/model/Country.scala
  tests/src/main/scala/ldbc/tests/model/CountryLanguage.scala
  tests/src/test/scala/ldbc/tests/SQLStringContextQueryTest.scala
Labels: 🔧 refactor, project:queryBuilder, project:dsl

#289 Hotfix/2024 09 fixed result set get by name
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/ResultSetImpl.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/ColumnDefinitionPacket.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ResultSetTest.scala
Labels: 🪲 bug, ldbc:connector

#295 Update doobie-core from 1.0.0-RC5 to 1.0.0-RC6
  project/Dependencies.scala
Labels: ⛓️ dependencies

#296 Update scala3-library from 3.5.0 to 3.5.1
  .github/workflows/ci.yml
  project/Versions.scala
Labels: ⛓️ dependencies

#292 Update sbt from 1.10.1 to 1.10.2
  project/build.properties
Labels: ⛓️ dependencies

#291 Refactor/2024 08 modification codec
  database/world.sql
  module/ldbc-codegen/shared/src/main/scala/ldbc/codegen/TableModelGenerator.scala
  module/ldbc-connector/js/src/test/scala/ldbc/connector/codec/NumericCodecsTest.scala
  module/ldbc-connector/jvm/src/test/scala/ldbc/connector/codec/NumericCodecsTest.scala
  module/ldbc-connector/native/src/test/scala/ldbc/connector/codec/NumericCodecsTest.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/ResultSetImpl.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/codec/NumericCodecs.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/Parameter.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ResultSetTest.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/Executor.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/Mysql.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/Parameter.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/Query.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/ResultSetConsumer.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/ResultSetReader.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/SQL.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/codec/Decoder.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/codec/Encoder.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/package.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/syntax/StringContextSyntax.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/Column.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/Table.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/interpreter/Tuples.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/Delete.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/Expression.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/GroupBy.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/Having.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/Insert.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/Join.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/Limit.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/Offset.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/OrderBy.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/Select.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/Update.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/Where.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/package.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/syntax/CommandSyntax.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/syntax/QuerySyntax.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/syntax/package.scala
  module/ldbc-query-builder/src/test/scala/ldbc/query/builder/QuerySyntaxTest.scala
  module/ldbc-query-builder/src/test/scala/ldbc/query/builder/TableQueryTest.scala
  module/ldbc-schema/src/main/scala/ldbc/schema/Alias.scala
  module/ldbc-schema/src/main/scala/ldbc/schema/ColumnImpl.scala
  module/ldbc-schema/src/main/scala/ldbc/schema/TableImpl.scala
  module/ldbc-schema/src/test/scala/ldbc/schema/AliasTest.scala
  module/ldbc-schema/src/test/scala/ldbc/schema/TableImplTest.scala
  tests/src/main/scala/ldbc/tests/model/Country.scala
  tests/src/main/scala/ldbc/tests/model/CountryLanguage.scala
  tests/src/test/scala/ldbc/tests/CodecTest.scala
  tests/src/test/scala/ldbc/tests/SQLStringContextQueryTest.scala
  tests/src/test/scala/ldbc/tests/TableQuerySelectConnectionTest.scala
  tests/src/test/scala/ldbc/tests/TableQueryUpdateConnectionTest.scala
Labels: 🔧 refactor, project:queryBuilder, project:dsl

#300 Refactor/2024 09 database term from option to default catalog
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/Connection.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/ConnectionImpl.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/DatabaseMetaDataImpl.scala
Labels: 🔧 refactor, ldbc:connector

#298 Update otel4s-core-trace from 0.9.0 to 0.10.0
  build.sbt
Labels: ⛓️ dependencies

#301 Update sbt-scalajs, scalajs-library_2.13, ... from 1.16.0 to 1.17.0
  project/plugins.sbt
Labels: ⛓️ dependencies

#294 Update mdoc, sbt-mdoc from 2.5.4 to 2.6.1
  project/plugins.sbt
Labels: ⛓️ dependencies

#303 Dependencies/2024 09 update scala version
  .github/workflows/ci.yml
  build.sbt
  module/ldbc-connector/native/src/main/scala/ldbc/connector/authenticator/Sha256PasswordPlugin.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/codec/Decoder.scala
  module/ldbc-hikari/src/main/scala/ldbc/hikari/HikariConfigBuilder.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/Column.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/Table.scala
  module/ldbc-query-builder/src/main/scala/ldbc/query/builder/statement/Join.scala
  module/ldbc-schema/src/main/scala/ldbc/schema/ColumnImpl.scala
  module/ldbc-schema/src/main/scala/ldbc/schema/TableImpl.scala
  project/Versions.scala
Labels: ⛓️ dependencies, project:core, project:queryBuilder, project:dsl, project:hikari, ldbc:connector, project:schema
