Repository takapi327/ldbc, pull requests merged in 2024-04, with the labels that each got.

#180 Feature/2024 03 add com statistics utility commands
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/Connection.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/CommandId.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/MySQLProtocol.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/package.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/request/ComStatisticsPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/StatisticsPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/UtilityCommands.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ConnectionTest.scala
Labels: 🚀 feature

#181 Feature/2024 04 add com ping utility commands
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/Connection.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/CommandId.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/MySQLProtocol.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/request/ComPingPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/UtilityCommands.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ConnectionTest.scala
Labels: 🚀 feature

#182 Feature/2024 04 add com reset connection utility commands
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/Connection.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/CommandId.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/MySQLProtocol.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/request/ComResetConnectionPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/UtilityCommands.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ConnectionTest.scala
Labels: 🚀 feature

#183 Feature/2024 04 add com set option utility commands
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/Connection.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/CommandId.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/EnumMySQLSetOption.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/MySQLProtocol.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/request/ComSetOptionPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/UtilityCommands.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ConnectionTest.scala
Labels: 🚀 feature

#184 Feature/2024 04 add com change user utility commands
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/Connection.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/CommandId.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/MySQLProtocol.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/request/ComChangeUserPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/Authentication.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ConnectionTest.scala
Labels: 🚀 feature

#185 Add Utility Commands document
  docs/src/main/mdoc/en/09-Connector.md
  docs/src/main/mdoc/ja/09-Connector.md
Labels: 📖 documentation

#188 Update sbt-site-paradox from 1.6.0 to 1.7.0
  project/plugins.sbt
Labels: ⛓️ dependencies

#186 Feature/2024 04 add batch command
  docs/src/main/mdoc/en/09-Connector.md
  docs/src/main/mdoc/ja/09-Connector.md
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/Connection.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/MySQLProtocol.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/PreparedStatement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/Statement.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ClientPreparedStatementUpdateTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ConnectionTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ServerPreparedStatementUpdateTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/StatementBatchTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/StatementQueryTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/StatementUpdateTest.scala
Labels: 🚀 feature, 🔧 refactor

#194 Refactor/2024 04 fix exception
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/Connection.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/SQLState.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/exception/BatchUpdateException.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/exception/ERRPacketException.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/exception/EofException.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/exception/MySQLException.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/exception/SQLClientInfoException.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/exception/SQLDataException.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/exception/SQLException.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/exception/SQLFeatureNotSupportedException.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/exception/SQLIntegrityConstraintViolationException.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/exception/SQLInvalidAuthorizationSpecException.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/exception/SQLNonTransientException.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/exception/SQLRecoverableException.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/exception/SQLSyntaxErrorException.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/exception/SQLTimeoutException.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/exception/SQLTransactionRollbackException.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/exception/SQLTransientConnectionException.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/exception/SQLTransientException.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/exception/UnknownPacketException.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/BitVectorSocket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/MySQLProtocol.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/ERRPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/Authentication.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/Initial.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/PreparedStatement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/Statement.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ConnectionTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/StatementBatchTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/TransactionTest.scala
Labels: 🔧 refactor

#190 Update slick from 3.5.0 to 3.5.1
  project/Dependencies.scala
Labels: ⛓️ dependencies

#187 Update README.md
  README.md
Labels: 📖 documentation

#195 Refactor/2024 04 fix result set
  docs/src/main/mdoc/en/09-Connector.md
  docs/src/main/mdoc/ja/09-Connector.md
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/Connection.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/ResultSet.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/ResultSetMetaData.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/CharsetMapping.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/MySQLProtocol.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/PreparedStatement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/Statement.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ClientPreparedStatementQueryTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ResultSetTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/SavepointTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ServerPreparedStatementQueryTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/StatementQueryTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/TransactionTest.scala
Labels: 🔧 refactor

#191 Update munit-cats-effect from 2.0.0-M4 to 2.0.0-M5
  build.sbt
Labels: ⛓️ dependencies

#196 Update sbt-typelevel from 0.6.7 to 0.7.0
  project/plugins.sbt
Labels: ⛓️ dependencies

#193 Update otel4s-core-trace from 0.5.0 to 0.6.0
  build.sbt
Labels: ⛓️ dependencies

#197 Refactor/2024 04 fix protocol
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/Connection.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/MySQLProtocol.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/Protocol.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/Authentication.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/PreparedStatement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/Statement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/UtilityCommands.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ConnectionTest.scala
Labels: 🔧 refactor
