Repository takapi327/ldbc, pull requests merged in 2024-03, with the labels that each got.

#144 Enhancement/2024 03 added scala3.4 version support
  .github/workflows/ci.yml
  build.sbt
  project/Versions.scala
Labels: enhancement

#130 Update slick from 3.5.0-M5 to 3.5.0-RC1
  project/Dependencies.scala
Labels: dependencies

#132 Update scalatest from 3.2.17 to 3.2.18
  project/Dependencies.scala
Labels: dependencies

#138 Update scala-library from 2.12.18 to 2.12.19
  project/Versions.scala
Labels: dependencies

#136 Update HikariCP from 5.0.1 to 5.1.0
  project/Dependencies.scala
Labels: dependencies

#139 Update mdoc, sbt-mdoc from 2.5.1 to 2.5.2
  project/plugins.sbt
Labels: dependencies

#140 Update specs2-core, specs2-junit from 5.4.0 to 5.4.2
  project/Dependencies.scala
Labels: dependencies

#141 Update doobie-core from 1.0.0-RC4 to 1.0.0-RC5
  project/Dependencies.scala
Labels: dependencies

#142 Update cats-effect from 3.5.2 to 3.5.3
  project/Dependencies.scala
Labels: dependencies

#145 Documentation/2024 03 fix docs
  README.md
  docs/src/main/mdoc/en/04-Database-Connection.md
  docs/src/main/mdoc/index.md
  docs/src/main/mdoc/ja/04-Database-Connection.md
  docs/src/main/mdoc/ja/07-Schema-Code-Generation.md
Labels: documentation

#152 Update scalafmt 3.7.17 -> 3.8.0
  .scalafmt.conf
Labels: dependencies

#128 Feature/2024 01 create ldbc connector project
  .github/workflows/ci.yml
  build.sbt
  database/mysql_user.sql
  docs/src/main/mdoc/ja/09-Connector.md
  docs/src/main/mdoc/ja/index.md
  module/ldbc-connector/js/src/main/scala/ldbc/connector/authenticator/CachingSha2PasswordPlugin.scala
  module/ldbc-connector/js/src/main/scala/ldbc/connector/authenticator/MysqlNativePasswordPlugin.scala
  module/ldbc-connector/js/src/main/scala/ldbc/connector/authenticator/Sha256PasswordPlugin.scala
  module/ldbc-connector/jvm/src/main/scala/ldbc/connector/authenticator/CachingSha2PasswordPlugin.scala
  module/ldbc-connector/jvm/src/main/scala/ldbc/connector/authenticator/MysqlNativePasswordPlugin.scala
  module/ldbc-connector/jvm/src/main/scala/ldbc/connector/authenticator/Sha256PasswordPlugin.scala
  module/ldbc-connector/native/src/main/scala/ldbc/connector/authenticator/CachingSha2PasswordPlugin.scala
  module/ldbc-connector/native/src/main/scala/ldbc/connector/authenticator/MysqlNativePasswordPlugin.scala
  module/ldbc-connector/native/src/main/scala/ldbc/connector/authenticator/Openssl.scala
  module/ldbc-connector/native/src/main/scala/ldbc/connector/authenticator/Sha256PasswordPlugin.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/Connection.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/SSL.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/authenticator/AuthenticationPlugin.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/CapabilitiesFlags.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/CommandId.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/ServerStatusFlags.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/exception/ERRPacketException.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/exception/EofException.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/exception/MySQLException.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/exception/UnknownPacketException.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/BitVectorSocket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/MySQLProtocol.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/PacketSocket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/SSLNegotiation.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/Packet.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/package.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/request/AuthSwitchResponsePacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/request/ComInitDBPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/request/ComQuitPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/request/HandshakeResponse320Packet.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/request/HandshakeResponse41Packet.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/request/HandshakeResponsePacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/request/SSLRequestPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/AuthMoreDataPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/AuthSwitchRequestPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/AuthenticationPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/EOFPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/ERRPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/GenericResponsePackets.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/InitialPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/OKPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/UnknownPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/Authentication.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/Exchange.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/Initial.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/package.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/util/Version.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ConnectionTest.scala
  project/Workflows.scala
Labels: feature

#154 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#134 Feature/2024 02 create statement for select query
  database/connector_test.sql
  database/world.sql
  database/world2.sql
  module/ldbc-connector/js/src/test/scala/ldbc/connector/codec/NumericCodecsTest.scala
  module/ldbc-connector/jvm/src/test/scala/ldbc/connector/codec/NumericCodecsTest.scala
  module/ldbc-connector/native/src/test/scala/ldbc/connector/codec/NumericCodecsTest.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/Connection.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/ResultSet.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/codec/BooleanCodec.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/codec/Codec.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/codec/Decoder.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/codec/Encoder.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/codec/NumericCodecs.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/codec/TemporalCodecs.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/codec/TextCodecs.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/codec/package.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/ColumnDataType.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/ColumnDefinitionFlags.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/Encoded.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/Type.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/exception/MySQLException.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/MySQLProtocol.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/package.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/request/BinaryProtocolValuePacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/request/ComQueryPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/request/package.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/ColumnDefinition320Packet.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/ColumnDefinition41Packet.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/ColumnDefinitionPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/ColumnsNumberPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/ERRPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/GenericResponsePackets.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/OKPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/ResultSetRowPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/Authentication.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/Statement.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ConnectionTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/StatementQueryTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/StatementUpdateTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/codec/BooleanCodecTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/codec/TemporalCodecsTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/codec/TextCodecsTest.scala
Labels: feature

#157 Enhancement/2024 03 add database login
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/Connection.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/BitVectorSocket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/MySQLProtocol.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/PacketSocket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/SSLNegotiation.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/request/HandshakeResponse320Packet.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/request/HandshakeResponse41Packet.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/request/HandshakeResponsePacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/request/SSLRequestPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/ERRPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/InitialPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/Authentication.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ConnectionTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/StatementUpdateTest.scala
Labels: enhancement

#158 Feature/2024 03 create prepared statement
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/Connection.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/ResultSet.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/codec/TemporalCodecs.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/Formatter.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/Parameter.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/MySQLProtocol.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/PreparedStatement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/Statement.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ClientPreparedStatementQueryTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ClientPreparedStatementUpdateTest.scala
Labels: feature

#159 Feature/2024 03 Create Server PreparedStatement
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/Connection.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/Parameter.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/MySQLProtocol.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/package.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/request/ComStmtClosePacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/request/ComStmtExecutePacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/request/ComStmtPreparePacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/BinaryProtocolResultSetRowPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/ComStmtPrepareOkPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/ResultSetRowPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/PreparedStatement.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ServerPreparedStatementQueryTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ServerPreparedStatementUpdateTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/StatementQueryTest.scala
Labels: feature

#146 Updating Documents
  README.md
  docs/src/main/mdoc/en/09-Connector.md
  docs/src/main/mdoc/en/index.md
  docs/src/main/mdoc/index.md
  docs/src/main/mdoc/ja/09-Connector.md
Labels: documentation

#151 Update specs2-core, specs2-junit from 5.4.2 to 5.5.1
  project/Dependencies.scala
Labels: dependencies

#166 Bug/2024 03 fix authentication
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/Authentication.scala
Labels: bug

#168 Fixed some settings in release.yml that were not enabled
  .github/release.yml
Labels: bug

#170 Change the Code of Conduct to that of the Typelevel community designation
  CODE_OF_CONDUCT.md
Labels: chore

#155 Update cats-effect from 3.5.3 to 3.5.4
  build.sbt
  project/Dependencies.scala
Labels: dependencies

#156 Update slick from 3.5.0-RC1 to 3.5.0
  project/Dependencies.scala
Labels: dependencies

#160 Update scala3-compiler, scala3-library from 3.3.1 to 3.3.3
  .github/workflows/ci.yml
  project/Versions.scala
Labels: dependencies

#165 Update sbt-typelevel from 0.6.5 to 0.6.7
  project/plugins.sbt
Labels: dependencies

#171 Update sbt-site-paradox from 1.5.0 to 1.6.0
  project/plugins.sbt
Labels: ⛓️ dependencies

#172 Update sbt-scalajs, scalajs-library_2.13, ... from 1.15.0 to 1.16.0
  project/plugins.sbt
Labels: ⛓️ dependencies

#174 Change label design
  .github/release.yml
Labels: 🔧 refactor

#173 Feature/2024 03 create savepoint
  docs/src/main/mdoc/en/09-Connector.md
  docs/src/main/mdoc/ja/09-Connector.md
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/Connection.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/Savepoint.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/SavepointTest.scala
Labels: 📖 documentation, 🚀 feature, ldbc:connector

#176 Update scala3-library from 3.4.0 to 3.4.1
  .github/workflows/ci.yml
  project/Versions.scala
Labels: ⛓️ dependencies

#179 Update otel4s-core-trace from 0.4.0 to 0.5.0
  build.sbt
Labels: ⛓️ dependencies

#178 Update scalafmt-core from 3.8.0 to 3.8.1
  .git-blame-ignore-revs
  .scalafmt.conf
  plugin/src/sbt-test/plugin/example/build.sbt
  plugin/src/sbt-test/plugin/example/project/plugins.sbt
Labels: ⛓️ dependencies

#177 Refactor/2024 03 fix com init db
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/Connection.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/MySQLProtocol.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/request/ComInitDBPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/response/InitialPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/Authentication.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/UtilityCommands.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ConnectionTest.scala
Labels: 🔧 refactor
