Repository takapi327/ldbc, pull requests merged in 2024-10, with the labels that each got.

#305 Dependencies/2024 10 update sbt typelevel
  .github/workflows/ci.yml
  project/plugins.sbt
Labels: ⛓️ dependencies

#304 Update slick from 3.5.1 to 3.5.2
  project/Dependencies.scala
Labels: ⛓️ dependencies

#306 Enhancement/2024 09 raises errors in fields that cannot be decoded
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/ResultSetImpl.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/ClientPreparedStatement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/ServerPreparedStatement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/StatementImpl.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/codec/Decoder.scala
  tests/src/test/scala/ldbc/tests/SQLStringContextQueryTest.scala
Labels: 🪲 bug, 💪 enhancement, ldbc:connector

#307 Enhancement/2024 10 added support tuple class mapping
  module/ldbc-dsl/src/main/scala/ldbc/dsl/codec/Decoder.scala
  tests/src/test/scala/ldbc/tests/SQLStringContextQueryTest.scala
Labels: 💪 enhancement, project:dsl

#247 Documentation/2024 06 fixed document
  .gitignore
  CONTRIBUTING.md
  README.md
  docs/src/main/mdoc/Migration-Notes.md
  docs/src/main/mdoc/directory.conf
  docs/src/main/mdoc/en/index.md
  docs/src/main/mdoc/en/reference/Connector.md
  docs/src/main/mdoc/en/reference/directory.conf
  docs/src/main/mdoc/en/tutorial/Connection.md
  docs/src/main/mdoc/en/tutorial/Custom-Data-Type.md
  docs/src/main/mdoc/en/tutorial/Database-Operations.md
  docs/src/main/mdoc/en/tutorial/Error-Handling.md
  docs/src/main/mdoc/en/tutorial/Logging.md
  docs/src/main/mdoc/en/tutorial/Parameterized-Queries.md
  docs/src/main/mdoc/en/tutorial/Query-Builder.md
  docs/src/main/mdoc/en/tutorial/Schema-Code-Generation.md
  docs/src/main/mdoc/en/tutorial/Schema.md
  docs/src/main/mdoc/en/tutorial/Selecting-Data.md
  docs/src/main/mdoc/en/tutorial/Setup.md
  docs/src/main/mdoc/en/tutorial/Simple-Program.md
  docs/src/main/mdoc/en/tutorial/Updating-Data.md
  docs/src/main/mdoc/en/tutorial/directory.conf
  docs/src/main/mdoc/img/data_multi_select.png
  docs/src/main/mdoc/img/data_select.png
  docs/src/main/mdoc/index.md
  docs/src/main/mdoc/ja/index.md
  docs/src/main/mdoc/ja/reference/Connector.md
  docs/src/main/mdoc/ja/reference/directory.conf
  docs/src/main/mdoc/ja/reference/index.md
  docs/src/main/mdoc/ja/tutorial/Connection.md
  docs/src/main/mdoc/ja/tutorial/Custom-Data-Type.md
  docs/src/main/mdoc/ja/tutorial/Database-Operations.md
  docs/src/main/mdoc/ja/tutorial/Error-Handling.md
  docs/src/main/mdoc/ja/tutorial/Logging.md
  docs/src/main/mdoc/ja/tutorial/Parameterized-Queries.md
  docs/src/main/mdoc/ja/tutorial/Query-Builder.md
  docs/src/main/mdoc/ja/tutorial/Schema-Code-Generation.md
  docs/src/main/mdoc/ja/tutorial/Schema.md
  docs/src/main/mdoc/ja/tutorial/Selecting-Data.md
  docs/src/main/mdoc/ja/tutorial/Setup.md
  docs/src/main/mdoc/ja/tutorial/Simple-Program.md
  docs/src/main/mdoc/ja/tutorial/Updating-Data.md
  docs/src/main/mdoc/ja/tutorial/directory.conf
  docs/src/main/mdoc/ja/tutorial/index.md
  docs/src/main/scala/00-Setup.scala
  docs/src/main/scala/01-Program.scala
  docs/src/main/scala/02-Program.scala
  docs/src/main/scala/03-Program.scala
  docs/src/main/scala/04-Program.scala
  docs/src/main/scala/05-Program.scala
  docs/src/main/scala/0X-Cleanup.scala
Labels: 📖 documentation

#308 Feature/2024 09 support versioned documentation
  build.sbt
  docs/src/main/mdoc/directory.conf
  docs/src/main/mdoc/en/directory.conf
  docs/src/main/mdoc/ja/directory.conf
  docs/src/main/mdoc/olderVersions/directory.conf
  docs/src/main/mdoc/olderVersions/index.md
  project/LaikaSettings.scala
  project/Versions.scala
Labels: 📖 documentation

#309 Rename scala34 -> scala35
  build.sbt
  project/Versions.scala
Labels: 🔧 refactor

#312 Update sbt-typelevel, ... from 0.7.3 to 0.7.4
  .github/workflows/ci.yml
  project/plugins.sbt
Labels: ⛓️ dependencies

#297 Update HikariCP from 5.1.0 to 6.0.0
  project/Dependencies.scala
Labels: ⛓️ dependencies

#315 Dependencies/2024 10 update scala version
  .github/workflows/ci.yml
  project/Versions.scala
Labels: ⛓️ dependencies

#319 Update sbt, scripted-plugin from 1.10.3 to 1.10.4
  project/build.properties
Labels: ⛓️ dependencies
