Repository takapi327/ldbc, pull requests merged in 2024-08, with the labels that each got.

#258 Update scalafmt-core from 3.8.2 to 3.8.3
  .scalafmt.conf
Labels: ⛓️ dependencies

#259 Update otel4s-core-trace from 0.8.0 to 0.8.1
  build.sbt
Labels: ⛓️ dependencies

#260 Update sbt-typelevel from 0.7.1 to 0.7.2
  .github/workflows/ci.yml
  project/plugins.sbt
Labels: ⛓️ dependencies

#267 Refactor/2024 08 change sync syntax helper function type
  module/ldbc-dsl/src/main/scala/ldbc/dsl/Mysql.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/package.scala
Labels: 🔧 refactor, project:dsl

#248 Refactor/2024 07 tracer and log handler as default noop
  module/ldbc-dsl/src/main/scala/ldbc/dsl/package.scala
  tests/src/test/scala/ldbc/tests/DDLTest.scala
  tests/src/test/scala/ldbc/tests/ExecutorTest.scala
  tests/src/test/scala/ldbc/tests/SQLStringContextQueryTest.scala
  tests/src/test/scala/ldbc/tests/SQLStringContextUpdateTest.scala
  tests/src/test/scala/ldbc/tests/TableQuerySelectConnectionTest.scala
  tests/src/test/scala/ldbc/tests/TableQueryUpdateConnectionTest.scala
Labels: 🔧 refactor, project:dsl

#240 Update nscplugin, sbt-scala-native from 0.4.17 to 0.5.4
  project/plugins.sbt
Labels: ⛓️ dependencies

#270 Update cats-core 2.10.0 -> 2.12.0
  build.sbt
Labels: ⛓️ dependencies

#268 Update scala-java-time 2.5.0 -> 2.6.0
  build.sbt
Labels: ⛓️ dependencies

#272 Update scodec
  build.sbt
Labels: ⛓️ dependencies

#274 Update specs2 4.20.5 -> 5.5.3
  build.sbt
Labels: ⛓️ dependencies

#275 Enhancement/2024 08 use scala native config brew
  .github/workflows/ci.yml
  build.sbt
  project/Workflows.scala
  project/plugins.sbt
Labels: 💪 enhancement

#133 Update sbt from 1.9.8 to 1.9.9
  project/build.properties
Labels: ⛓️ dependencies

#279 Update scala3-library from 3.4.2 to 3.4.3
  .github/workflows/ci.yml
  project/Versions.scala
Labels: ⛓️ dependencies

#281 Bug/2024 08 fixed helper function values
  benchmark/src/main/scala/benchmark/wrapper/ldbc/Insert.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/package.scala
  module/ldbc-dsl/src/test/scala/ldbc/dsl/HelperFunctionTest.scala
Labels: 🪲 bug, project:dsl

#273 Update fs2 3.10-365636d -> 3.10.2
  build.sbt
  module/ldbc-connector/js-jvm/src/test/scala/ldbc/connector/package.scala
  module/ldbc-connector/native/src/test/scala/ldbc/connector/package.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/CallableStatementTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ClientPreparedStatementQueryTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ClientPreparedStatementUpdateTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ConnectionTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ResultSetTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/SavepointTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ServerPreparedStatementQueryTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ServerPreparedStatementUpdateTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/StatementBatchTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/StatementQueryTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/StatementUpdateTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/TransactionTest.scala
Labels: ⛓️ dependencies

#284 Update fs2-core, fs2-io from 3.10.2 to 3.11.0
  build.sbt
Labels: ⛓️ dependencies
