Repository takapi327/ldbc, pull requests merged in 2025-06, with the labels that each got.

#484 Update sbt, scripted-plugin from 1.11.0 to 1.11.1
  project/build.properties
Labels: ⛓️ dependencies

#490 Update opentelemetry-exporter-otlp, ... from 1.50.0 to 1.51.0
  build.sbt
Labels: ⛓️ dependencies

#488 Bugfix/2025 06 Fix jdbc connector
  module/jdbc-connector/src/main/scala/jdbc/connector/ConnectionProvider.scala
Labels: 🪲 bug, jdbc:connector

#494 Update sbt, scripted-plugin from 1.11.1 to 1.11.2
  project/build.properties
Labels: ⛓️ dependencies

#497 Update circe-yaml from 0.16.0 to 0.16.1
  build.sbt
Labels: ⛓️ dependencies

#500 Feature/2025 06 added stream support
  .github/workflows/ci.yml
  benchmark/src/main/scala/benchmark/connector/jdbc/Select.scala
  benchmark/src/main/scala/benchmark/connector/ldbc/Select.scala
  build.sbt
  module/jdbc-connector/src/main/scala/jdbc/connector/DatabaseMetaDataImpl.scala
  module/jdbc-connector/src/main/scala/jdbc/connector/PreparedStatementImpl.scala
  module/jdbc-connector/src/main/scala/jdbc/connector/ResultSetImpl.scala
  module/jdbc-connector/src/main/scala/jdbc/connector/StatementImpl.scala
  module/ldbc-connector/js/src/test/scala/ldbc/connector/TLSConnectionTest.scala
  module/ldbc-connector/jvm/src/test/scala/ldbc/connector/TLSConnectionTest.scala
  module/ldbc-connector/native/src/test/scala/ldbc/connector/TLSConnectionTest.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/Connection.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/ConnectionImpl.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/ConnectionProvider.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/DatabaseMetaDataImpl.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/ResultSetImpl.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/SharedResultSet.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/StreamingResultSet.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/data/CommandId.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/request/ComStmtExecutePacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/packet/request/ComStmtFetchPacket.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/CallableStatementImpl.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/ClientPreparedStatement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/ServerPreparedStatement.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/StatementImpl.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/syntax/ResultSetOps.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/syntax/package.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/CallableStatementTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ClientPreparedStatementQueryTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ConnectionTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ResultSetTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/SavepointTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ServerCursorFetchTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ServerPreparedStatementQueryTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/StatementQueryTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/StatementUpdateTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/TransactionTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/net/protocol/SharedPreparedStatementTest.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/DBIO.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/ResultSetConsumer.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/codec/Codec.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/codec/Decoder.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/free/ResultSetIO.scala
  module/ldbc-dsl/src/test/scala/ldbc/dsl/codec/DecoderTest.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/DatabaseMetaData.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/PreparedStatement.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/ResultSet.scala
  module/ldbc-sql/src/main/scala/ldbc/sql/Statement.scala
  module/ldbc-statement/src/main/scala/ldbc/statement/Column.scala
  tests/jvm/src/test/scala/ldbc/tests/JdbcSQLStringContextQueryTest.scala
  tests/jvm/src/test/scala/ldbc/tests/JdbcServerCursorFetchTest.scala
  tests/shared/src/test/scala/ldbc/tests/ConnectionTest.scala
  tests/shared/src/test/scala/ldbc/tests/DatabaseMetaDataTest.scala
  tests/shared/src/test/scala/ldbc/tests/SQLStringContextQueryTest.scala
  tests/shared/src/test/scala/ldbc/tests/ServerCursorFetchTest.scala
Labels: 🚀 feature, project:dsl, ldbc:connector, jdbc:connector
