Repository takapi327/ldbc, pull requests merged in 2025-05, with the labels that each got.

#460 Update scalafmt-core from 3.9.4 to 3.9.5
  .scalafmt.conf
Labels: ⛓️ dependencies

#457 Feature/2024 05 craete mcp server
  .github/workflows/ci.yml
  .github/workflows/npmPublish.yml
  README.md
  build.sbt
  docker-compose.yml
  docs/src/main/mdoc/en/tutorial/Setup.md
  docs/src/main/mdoc/ja/tutorial/Setup.md
  mcp/document-server/.js/README.md
  mcp/document-server/.js/src/main/scala/ldbc/mcp/PathUtils.scala
  mcp/document-server/.js/src/main/scala/ldbc/mcp/StdioServer.scala
  mcp/document-server/.js/src/main/scala/ldbc/mcp/Tools.scala
  project/plugins.sbt
Labels: 📖 documentation

#462 Update scalafmt-core from 3.9.5 to 3.9.6
  .scalafmt.conf
Labels: ⛓️ dependencies

#465 Refactor/2025 05 scala 3.7 support for tests
  .github/workflows/ci.yml
  build.sbt
  tests/src/test/scala/ldbc/tests/DBIOTest.scala
Labels: 🔧 refactor

#463 Enhancement/2025 05 support named tuple
  build.sbt
  module/ldbc-dsl/src/main/scala/ldbc/dsl/codec/Decoder.scala
  tests/.jvm/src/test/scala-3.7/ldbc/tests/NamedTupleDecoderTest.scala
Labels: 💪 enhancement

#468 Refactor/2025 05 multi platform support for tests
  .github/workflows/ci.yml
  build.sbt
  tests/jvm/src/main/scala/ldbc/tests/JdbcConnectionFixture.scala
  tests/jvm/src/test/scala/ldbc/tests/JdbcCodecTest.scala
  tests/jvm/src/test/scala/ldbc/tests/JdbcConnectionTest.scala
  tests/jvm/src/test/scala/ldbc/tests/JdbcDDLTest.scala
  tests/jvm/src/test/scala/ldbc/tests/JdbcDatabaseMetaDataTest.scala
  tests/jvm/src/test/scala/ldbc/tests/JdbcSQLStringContextQueryTest.scala
  tests/jvm/src/test/scala/ldbc/tests/JdbcSQLStringContextUpdateTest.scala
  tests/jvm/src/test/scala/ldbc/tests/JdbcTableQuerySelectConnectionTest.scala
  tests/jvm/src/test/scala/ldbc/tests/JdbcTableQueryUpdateConnectionTest.scala
  tests/jvm/src/test/scala/ldbc/tests/JdbcTableSchemaSelectConnectionTest.scala
  tests/jvm/src/test/scala/ldbc/tests/JdbcTableSchemaUpdateConnectionTest.scala
  tests/shared/src/main/scala/ldbc/tests/ConnectionFixture.scala
  tests/shared/src/main/scala/ldbc/tests/model/City.scala
  tests/shared/src/main/scala/ldbc/tests/model/Country.scala
  tests/shared/src/main/scala/ldbc/tests/model/CountryLanguage.scala
  tests/shared/src/main/scala/ldbc/tests/model/GovernmentOffice.scala
  tests/shared/src/test/scala/ldbc/tests/CodecTest.scala
  tests/shared/src/test/scala/ldbc/tests/ConnectionTest.scala
  tests/shared/src/test/scala/ldbc/tests/DBIOTest.scala
  tests/shared/src/test/scala/ldbc/tests/DDLTest.scala
  tests/shared/src/test/scala/ldbc/tests/DatabaseMetaDataTest.scala
  tests/shared/src/test/scala/ldbc/tests/SQLStringContextQueryTest.scala
  tests/shared/src/test/scala/ldbc/tests/SQLStringContextUpdateTest.scala
  tests/shared/src/test/scala/ldbc/tests/TableQuerySelectConnectionTest.scala
  tests/shared/src/test/scala/ldbc/tests/TableQueryUpdateConnectionTest.scala
  tests/shared/src/test/scala/ldbc/tests/TableSchemaSelectConnectionTest.scala
  tests/shared/src/test/scala/ldbc/tests/TableSchemaUpdateConnectionTest.scala
  tests/src/test/scala/ldbc/tests/CodecTest.scala
  tests/src/test/scala/ldbc/tests/SQLStringContextUpdateTest.scala
Labels: 🔧 refactor

#469 Update opentelemetry-exporter-otlp, ... from 1.49.0 to 1.50.0
  build.sbt
Labels: ⛓️ dependencies

#470 Enhancement/2025 05 support enum
  build.sbt
  docs/src/main/mdoc/en/qa/How-do-I-use-the-Enum-type.md
  docs/src/main/mdoc/en/qa/directory.conf
  docs/src/main/mdoc/en/tutorial/Schema.md
  docs/src/main/mdoc/ja/qa/How-do-I-use-the-Enum-type.md
  docs/src/main/mdoc/ja/qa/directory.conf
  docs/src/main/mdoc/ja/tutorial/Schema.md
  mcp/document-server/.js/src/main/scala/ldbc/mcp/Tools.scala
  module/ldbc-codegen/shared/src/main/scala/ldbc/codegen/TableModelGenerator.scala
  module/ldbc-codegen/shared/src/main/scala/ldbc/codegen/builder/DataTypeCodeBuilder.scala
  module/ldbc-codegen/shared/src/test/scala/ldbc/codegen/builder/DataTypeCodeBuilderTest.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/codec/Codec.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/codec/Decoder.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/codec/Encoder.scala
  module/ldbc-dsl/src/main/scala/ldbc/dsl/util/Mirrors.scala
  module/ldbc-schema/.js/src/test/scala/ldbc/schema/DataTypeTest.scala
  module/ldbc-schema/.jvm/src/test/scala/ldbc/schema/DataTypeTest.scala
  module/ldbc-schema/.native/src/test/scala/ldbc/schema/DataTypeTest.scala
  module/ldbc-schema/src/main/scala/ldbc/schema/Character.scala
  module/ldbc-schema/src/main/scala/ldbc/schema/DataType.scala
  module/ldbc-schema/src/main/scala/ldbc/schema/DataTypes.scala
  module/ldbc-schema/src/main/scala/ldbc/schema/Table.scala
  module/ldbc-schema/src/main/scala/ldbc/schema/model/EnumDataType.scala
  module/ldbc-schema/src/test/scala/ldbc/schema/TableCreateStatementTest.scala
  module/ldbc-statement/src/main/scala/ldbc/statement/interpreter/Extract.scala
  plugin/src/sbt-test/plugin/example/build.sbt
  plugin/src/sbt-test/plugin/example/test
  tests/jvm/src/test/scala/ldbc/tests/JdbcSQLStringContextQueryTest.scala
  tests/shared/src/test/scala/ldbc/tests/SQLStringContextQueryTest.scala
Labels: 💪 enhancement, project:dsl, project:schema

#471 Enhancement/2025 05 introducing codecoverage
  .github/workflows/ci.yml
  README.md
  build.sbt
  codecov.yml
  docs/src/main/mdoc/README.md
  docs/src/main/mdoc/index.md
  project/Workflows.scala
  project/plugins.sbt
Labels: 💪 enhancement

#472 Added scaladoc badge
  README.md
  docs/src/main/mdoc/README.md
  docs/src/main/mdoc/index.md
Labels: 📖 documentation

#475 Enhancement/2025 05 correction of coverages testing omissions
  module/ldbc-statement/src/test/scala/ldbc/statement/ColumnTest.scala
  module/ldbc-statement/src/test/scala/ldbc/statement/ExpressionTest.scala
  module/ldbc-statement/src/test/scala/ldbc/statement/GroupByTest.scala
  module/ldbc-statement/src/test/scala/ldbc/statement/InsertTest.scala
  module/ldbc-statement/src/test/scala/ldbc/statement/OrderByTest.scala
  module/ldbc-statement/src/test/scala/ldbc/statement/SchemaTest.scala
  module/ldbc-statement/src/test/scala/ldbc/statement/WhereTest.scala
  module/ldbc-statement/src/test/scala/ldbc/statement/formatter/NamingTest.scala
Labels: 💪 enhancement, project:statement

#476 Update slick from 3.6.0 to 3.6.1
  project/Dependencies.scala
Labels: ⛓️ dependencies

#478 Refactor/2025-05 Update test
  build.sbt
  codecov.yml
  module/ldbc-schema/.js/src/test/scala/ldbc/schema/DataTypeTest.scala
  module/ldbc-schema/.js/src/test/scala/ldbc/schema/JsDataTypeTest.scala
  module/ldbc-schema/.jvm/src/test/scala/ldbc/schema/DataTypeTest.scala
  module/ldbc-schema/.jvm/src/test/scala/ldbc/schema/JvmDataTypeTest.scala
  module/ldbc-schema/.native/src/test/scala/ldbc/schema/DataTypeTest.scala
  module/ldbc-schema/.native/src/test/scala/ldbc/schema/NativeDataTypeTest.scala
  module/ldbc-schema/src/main/scala/ldbc/schema/DataType.scala
  module/ldbc-schema/src/main/scala/ldbc/schema/DataTypes.scala
  module/ldbc-schema/src/test/scala/ldbc/schema/DataTypeTest.scala
  module/ldbc-schema/src/test/scala/ldbc/schema/attribute/AutoIncTest.scala
  tests/shared/src/test/scala/ldbc/tests/ConnectionTest.scala
  tests/shared/src/test/scala/ldbc/tests/DatabaseMetaDataTest.scala
Labels: 🔧 refactor

#479 Enhancement/2025 05 correction of coverages testing omissions
  build.sbt
  module/ldbc-codegen/shared/src/main/scala/ldbc/codegen/DatabaseModelGenerator.scala
  module/ldbc-codegen/shared/src/main/scala/ldbc/codegen/LdbcGenerator.scala
  module/ldbc-codegen/shared/src/main/scala/ldbc/codegen/TableModelGenerator.scala
  module/ldbc-codegen/shared/src/main/scala/ldbc/codegen/builder/ColumnCodeBuilder.scala
  module/ldbc-codegen/shared/src/main/scala/ldbc/codegen/builder/DataTypeCodeBuilder.scala
  module/ldbc-codegen/shared/src/main/scala/ldbc/codegen/formatter/Naming.scala
  module/ldbc-codegen/shared/src/main/scala/ldbc/codegen/model/ColumnDefinition.scala
  module/ldbc-codegen/shared/src/main/scala/ldbc/codegen/model/Comment.scala
  module/ldbc-codegen/shared/src/main/scala/ldbc/codegen/model/Key.scala
  module/ldbc-codegen/shared/src/test/scala/ldbc/codegen/builder/ColumnCodeBuilderTest.scala
  module/ldbc-codegen/shared/src/test/scala/ldbc/codegen/builder/DataTypeCodeBuilderTest.scala
  module/ldbc-codegen/shared/src/test/scala/ldbc/codegen/formatter/NamingTest.scala
  module/ldbc-codegen/shared/src/test/scala/ldbc/codegen/model/ColumnDefinitionTest.scala
  module/ldbc-codegen/shared/src/test/scala/ldbc/codegen/model/KeyTest.scala
Labels: 💪 enhancement, project:codegen

#480 Enhancement/2025 05 correction of coverages testing omissions
  codecov.yml
  module/ldbc-dsl/src/test/scala/ldbc/dsl/codec/DecoderTest.scala
  module/ldbc-dsl/src/test/scala/ldbc/dsl/codec/EncoderTest.scala
Labels: 💪 enhancement, project:dsl

#481 Enhancement/2025 05 used nix
  flake.lock
  flake.nix
Labels: 💪 enhancement
