Repository takapi327/ldbc, pull requests merged in 2025-09, with the labels that each got.

#531 Update sbt-scalajs, scalajs-library_2.13, ... from 1.19.0 to 1.20.1
  project/plugins.sbt
Labels: ⛓️ dependencies

#530 Update opentelemetry-exporter-otlp, ... from 1.53.0 to 1.54.0
  build.sbt
Labels: ⛓️ dependencies

#535 Updates to the Performance Document
  benchmark/src/main/scala/benchmark/connector/jdbc/Select.scala
  benchmark/src/main/scala/benchmark/connector/ldbc/Select.scala
  docs/src/main/mdoc/en/reference/Performance.md
  docs/src/main/mdoc/img/connector/Select_Thread1.svg
  docs/src/main/mdoc/img/connector/Select_Thread16.svg
  docs/src/main/mdoc/img/connector/Select_Thread2.svg
  docs/src/main/mdoc/img/connector/Select_Thread4.svg
  docs/src/main/mdoc/img/connector/Select_Thread8.svg
  docs/src/main/mdoc/ja/reference/Performance.md
  script/python/visualize.py
Labels: 📖 documentation

#532 Update sbt, scripted-plugin from 1.11.5 to 1.11.6
  project/build.properties
Labels: ⛓️ dependencies

#537 Documentation/2025 09 update use new syntax
  docs/src/main/mdoc/README.md
  docs/src/main/mdoc/en/examples/HikariCP.md
  docs/src/main/mdoc/en/examples/Http4s.md
  docs/src/main/mdoc/en/examples/Otel.md
  docs/src/main/mdoc/en/qa/How-to-handle-multiple-databases.md
  docs/src/main/mdoc/en/qa/How-to-perform-DDL-with-schema.md
  docs/src/main/mdoc/en/qa/How-to-use-with-ZIO.md
  docs/src/main/mdoc/en/qa/Is-there-a-function-to-limit-the-number-of-concurrent-queries.md
  docs/src/main/mdoc/en/qa/What-is-ldbc.md
  docs/src/main/mdoc/en/qa/What-is-the-difference-between-a-Java-connect-and-a-Scala-connector.md
  docs/src/main/mdoc/en/qa/Which-dependencies-should-I-set.md
  docs/src/main/mdoc/en/reference/Connector.md
  docs/src/main/mdoc/en/tutorial/Connection.md
  docs/src/main/mdoc/en/tutorial/Error-Handling.md
  docs/src/main/mdoc/en/tutorial/Logging.md
  docs/src/main/mdoc/en/tutorial/Parameterized-Queries.md
  docs/src/main/mdoc/en/tutorial/Query-Builder.md
  docs/src/main/mdoc/en/tutorial/Schema-Code-Generation.md
  docs/src/main/mdoc/en/tutorial/Schema.md
  docs/src/main/mdoc/en/tutorial/Selecting-Data.md
  docs/src/main/mdoc/en/tutorial/Setup.md
  docs/src/main/mdoc/en/tutorial/Simple-Program.md
  docs/src/main/mdoc/en/tutorial/Updating-Data.md
  docs/src/main/mdoc/en/tutorial/index.md
  docs/src/main/mdoc/index.md
  docs/src/main/mdoc/ja/examples/HikariCP.md
  docs/src/main/mdoc/ja/examples/Http4s.md
  docs/src/main/mdoc/ja/examples/Otel.md
  docs/src/main/mdoc/ja/qa/How-do-I-add-processing-before-and-after-the-connection-is-established.md
  docs/src/main/mdoc/ja/qa/How-to-handle-multiple-databases.md
  docs/src/main/mdoc/ja/qa/How-to-perform-DDL-with-schema.md
  docs/src/main/mdoc/ja/qa/How-to-use-with-ZIO.md
  docs/src/main/mdoc/ja/qa/Is-there-a-function-to-limit-the-number-of-concurrent-queries.md
  docs/src/main/mdoc/ja/qa/What-is-ldbc.md
  docs/src/main/mdoc/ja/qa/What-is-the-difference-between-a-Java-connect-and-a-Scala-connector.md
  docs/src/main/mdoc/ja/qa/Which-dependencies-should-I-set.md
  docs/src/main/mdoc/ja/reference/Connector.md
  docs/src/main/mdoc/ja/tutorial/Connection.md
  docs/src/main/mdoc/ja/tutorial/Error-Handling.md
  docs/src/main/mdoc/ja/tutorial/Logging.md
  docs/src/main/mdoc/ja/tutorial/Parameterized-Queries.md
  docs/src/main/mdoc/ja/tutorial/Query-Builder.md
  docs/src/main/mdoc/ja/tutorial/Schema-Code-Generation.md
  docs/src/main/mdoc/ja/tutorial/Schema.md
  docs/src/main/mdoc/ja/tutorial/Selecting-Data.md
  docs/src/main/mdoc/ja/tutorial/Setup.md
  docs/src/main/mdoc/ja/tutorial/Simple-Program.md
  docs/src/main/mdoc/ja/tutorial/Updating-Data.md
  docs/src/main/mdoc/ja/tutorial/index.md
Labels: 📖 documentation

#534 Update scala3-compiler, scala3-library, ... from 3.7.2 to 3.7.3
  .github/workflows/ci.yml
  project/Versions.scala
Labels: ⛓️ dependencies

#542 Enhancement/2025 09 added pool status reporter
  docs/src/main/mdoc/en/tutorial/Connection.md
  docs/src/main/mdoc/ja/tutorial/Connection.md
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/MySQLConfig.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/MySQLDataSource.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/pool/CircuitBreaker.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/pool/HouseKeeper.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/pool/PoolLogger.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/pool/PoolMetricsTracker.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/pool/PoolStatusReporter.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/pool/PooledDataSource.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/MySQLDataSourceTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/pool/CircuitBreakerTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/pool/KeepaliveExecutorTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/pool/PoolLoggerTest.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/pool/PoolStatusReporterTest.scala
  tests/js/src/test/scala/ldbc/tests/ConnectionPoolDslTest.scala
  tests/jvm/src/test/scala/ldbc/tests/ConnectionPoolDslTest.scala
Labels: 💪 enhancement, ldbc:connector

#541 Update opentelemetry-exporter-otlp, ... from 1.54.0 to 1.54.1
  build.sbt
Labels: ⛓️ dependencies

#549 Refactor/2025 09 added tracer property
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/MySQLDataSource.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/pool/PooledDataSource.scala
Labels: 🔧 refactor, ldbc:connector

#551 Delete schemaspy dependencies
  project/Dependencies.scala
Labels: ⛓️ dependencies

#557 Refactor/2025 09 delete connection provider
  docs/src/main/scala/01-Program.scala
  docs/src/main/scala/02-Program.scala
  docs/src/main/scala/03-Program.scala
  docs/src/main/scala/04-Program.scala
  docs/src/main/scala/05-Program.scala
  docs/src/main/scala/0X-Cleanup.scala
  examples/http4s/src/main/scala/Main.scala
  examples/otel/src/main/scala/Main.scala
  module/jdbc-connector/src/main/scala/jdbc/connector/ConnectionProvider.scala
  module/jdbc-connector/src/main/scala/jdbc/connector/package.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/ConnectionProvider.scala
  module/ldbc-connector/shared/src/main/scala/ldbc/connector/package.scala
  module/ldbc-connector/shared/src/test/scala/ldbc/connector/ConnectionProviderTest.scala
Labels: 🔧 refactor, ldbc:connector, jdbc:connector
